// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class md_addrecorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(md_addrecorder));
        
        string IMigrationMetadata.Id
        {
            get { return "202004230635273_md_addrecorder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
